vm_power:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: vsphere
    action:
      required: true
      selector:
        select:
          options:
            - power_on
            - power_off
            - shutdown
            - reboot
            - reset
            - suspend

host_power:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: vsphere
    action:
      required: true
      selector:
        select:
          options:
            - shutdown
            - reboot
    force:
      required: false
      default: false
      selector:
        boolean:

host_power_policy:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: vsphere
    policy:
      required: true
      selector:
        text:

host_maintenance_mode:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: vsphere
    enable:
      required: true
      selector:
        boolean:

create_snapshot:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: vsphere
    name:
      required: false
      selector:
        text:
    description:
      required: false
      selector:
        text:
    memory:
      required: false
      default: false
      selector:
        boolean:
    quiesce:
      required: false
      default: false
      selector:
        boolean:

remove_snapshot:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: vsphere
    which:
      required: true
      selector:
        select:
          options:
            - all
            - first
            - last

list_hosts:
  response_supported: true
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: vsphere

list_power_policies:
  response_supported: true
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: vsphere

vm_migrate:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: vsphere
    target_host:
      required: true
      selector:
        device:
          integration: vsphere

remove_snapshots:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: vsphere
    snapshots:
      required: true
      selector:
        object:
